[package]
name = "ray-tracing-the-next-week"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.5.4"
config = "0.14.0"
num = "0.4.1"
rand = "0.8.5"
